### ISSUE TITLE
Pequena mudança realizada e sugestão

### ISSUE THREAD

**Issue by Mysael** [wesleygonalv/LSI-18.1-TrovaLaMacchina#25]
Victor, eu dei uma pequena alterada lá no teu css do simulador:
#flutuante {
    float: left;
    margin-right: 3%;
    margin-top: 5%;
    margin-left: 4%;
}
Trocando esse valor da "margin-left: 4%;" para 2%, pq na hora da exibição dentro do container, estava ocupando mais espaço e nn deixava que todos os elementos se mantivessem no mesmo alinhamento.

Ah, tbm notei que pode ser removido um elemento lá para reduzir o espaço ocupado.
de:
```
<div id="flutuante">
    <label>Final date</label>
    <br>
    <input type="date">
  </div>
  <div id="flutuante">
    <label></label>
    <p>=</p>
  </div>
  <div id="flutuante">
    <label>Final Price</label>
    <h5>1000 &euro;</h5>
  </div>
```
para:
```
  <div id="flutuante">
    <label>Final date</label>
    <br>
    <input type="date">
  </div>
  <div id="flutuante">
    <label>Final Price</label>
    <h5>= 1000 &euro;</h5>
  </div>
```
(o simbolo de igualdade pulou para o lado do valor (1000 euros)

**Comment by VictorNobrega** [comment]
Tranquilo.
